# Generated by Django 3.2.12 on 2022-04-26 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DPC_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DPC_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DPC_TaxLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DPC_urlparam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlparam', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DPC_TaxonomyTerm',
            fields=[
                ('status', model_utils.fields.StatusField(choices=[('removed', 'removed'), ('published', 'published')], default='removed', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('code', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='catalog.dpc_code')),
                ('desc', models.CharField(max_length=255)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.dpc_taxlibrary')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalog.dpc_name')),
                ('urlparam', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='catalog.dpc_urlparam')),
            ],
            options={
                'db_table': 'DPC_TaxonomyTerm',
                'abstract': False,
            },
        ),
    ]
