# Generated by Django 3.2.12 on 2022-04-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dpc_taxonomyterm',
            table=None,
        ),
    ]
