# Generated by Django 3.2.12 on 2022-04-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_dpc_taxonomyterm_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpc_taxlibrary',
            options={'verbose_name': 'Taxonomy Library'},
        ),
        migrations.AlterModelOptions(
            name='dpc_taxonomyterm',
            options={'verbose_name': 'Taxonomy Term'},
        ),
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='urlparam',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='DPC_code',
        ),
        migrations.DeleteModel(
            name='DPC_name',
        ),
        migrations.DeleteModel(
            name='DPC_urlparam',
        ),
    ]
