# Generated by Django 3.2.12 on 2022-04-27 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220427_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='urlparam',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9_]{3,20}$', message='Code must be at least 3 and max 10 Alpha-Numeric, LOWERCase with Optional Underscores Only: EX: ABC_ABC')]),
        ),
    ]
