# Generated by Django 3.2.12 on 2022-04-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20220427_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
