# Generated by Django 3.2.12 on 2022-04-27 13:17

import django.core.validators
from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_dpc_taxonomyterm_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='published', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='urlparam',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]{3,30}$', message='Code must be at least 3 and max 30 Alpha-Numeric, LOWERCase with Optional Hyphens Only: EX: ABC-ABC')]),
        ),
    ]
