# Generated by Django 3.2.12 on 2022-04-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_dpc_academicpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpc_academicpage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dpc_academicpage',
            name='taxonomy_term',
        ),
        migrations.AddField(
            model_name='dpc_academicpage',
            name='class_type',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('library__name', 'Class Type')), related_name='academicpage_classtype', to='catalog.DPC_TaxonomyTerm'),
        ),
        migrations.AddField(
            model_name='dpc_academicpage',
            name='faculty_department',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('library__name', 'Faculty Deparment')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academicpage_facultydepartment', to='catalog.dpc_taxonomyterm'),
        ),
        migrations.AddField(
            model_name='dpc_academicpage',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('library__name', 'Field of Study')), related_name='academicpage_fieldofstudy', to='catalog.DPC_TaxonomyTerm'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='body_a',
            field=models.TextField(help_text='HTML in the top portion of the page.  Not HTML validated, Do not edit here, be careful.'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='body_b',
            field=models.TextField(help_text='HTML in the bottom portion of the page.  Not HTML validated, Do not edit here, be careful.'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='parent_code',
            field=models.ForeignKey(blank=True, default='', help_text='This will unite this program with another program in a relationship such as Major/Concentration.', limit_choices_to={'status': 'published'}, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.dpc_academicpage', to_field='unique_program_code'),
        ),
    ]
