# Generated by Django 3.2.12 on 2022-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20220428_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpc_academicpage',
            name='class_type',
        ),
        migrations.AddField(
            model_name='dpc_academicpage',
            name='class_format',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('library__name', 'Class Format')), related_name='academicpage_classformat', to='catalog.DPC_TaxonomyTerm'),
        ),
    ]
