# Generated by Django 3.2.12 on 2022-04-28 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20220428_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='body_a',
            field=models.TextField(help_text='HTML in the top portion of the page.  Not HTML validated, Do not edit here, be careful.', verbose_name='Body A HTML'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='body_b',
            field=models.TextField(help_text='HTML in the bottom portion of the page.  Not HTML validated, Do not edit here, be careful.', verbose_name='Body B HTML'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='class_format',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('library__name', 'Class Format')), related_name='academicpage_classformat', to='catalog.DPC_TaxonomyTerm', verbose_name='Class Format'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='faculty_department',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('library__name', 'Faculty Deparment')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academicpage_facultydepartment', to='catalog.dpc_taxonomyterm', verbose_name='Faculty Department'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='field_of_study',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('library__name', 'Field of Study')), related_name='academicpage_fieldofstudy', to='catalog.DPC_TaxonomyTerm', verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='parent_code',
            field=models.ForeignKey(blank=True, default='', help_text='This will unite this program with another program in a relationship such as Major/Concentration.', limit_choices_to={'status': 'published'}, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.dpc_academicpage', to_field='unique_program_code', verbose_name='Parent Code'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='program_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('library__name', 'Program Type')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academicpage_programtype', to='catalog.dpc_taxonomyterm', verbose_name='Program Type'),
        ),
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='urlparam',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]{3,30}$', message='Code must be at least 3 and max 30 Alpha-Numeric, LOWERCase with Optional Hyphens Only: EX: ABC-ABC')]),
        ),
    ]
