# Generated by Django 3.2.12 on 2022-04-28 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20220428_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dpc_academicpage',
            name='faculty_department',
        ),
        migrations.AddField(
            model_name='dpc_academicpage',
            name='faculty_department',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('library__name', 'Faculty Deparment')), related_name='academicpage_facultydepartment', to='catalog.DPC_TaxonomyTerm', verbose_name='Faculty Department'),
        ),
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='urlparam',
            field=models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9\\-]{3,40}$', message='Code must be at least 3 and max 30 Alpha-Numeric, LOWERCase with Optional Hyphens Only: EX: ABC-ABC')]),
        ),
    ]
