# Generated by Django 3.2.12 on 2022-04-28 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20220428_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpc_academicpage',
            name='degree_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('library__name', 'Degree Type')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academicpage_degreetype', to='catalog.dpc_taxonomyterm', verbose_name='Degree Type'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='faculty_department',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('library__name', 'Faculty Department')), related_name='academicpage_facultydepartment', to='catalog.DPC_TaxonomyTerm', verbose_name='Faculty Department'),
        ),
    ]
