# Generated by Django 3.2.12 on 2022-04-28 14:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_auto_20220428_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='parent_code',
            field=models.ForeignKey(blank=True, default='', help_text='This will unite this program with another program in a relationship such as Major/Concentration.', limit_choices_to={'status': 'published'}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.dpc_academicpage', to_field='unique_program_code', verbose_name='Parent Code'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9,.\\(\\)\\- ]{5,150}$', message='Title must be at least 5 and max 150 Alpha-Numeric Characters, may the following punctionation characters: ,.()-_')]),
        ),
    ]
