# Generated by Django 3.2.12 on 2022-04-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20220428_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='body_a',
            field=models.TextField(blank=True, default='', help_text='HTML in the top portion of the page.  Not HTML validated, Do not edit here, be careful.', verbose_name='Body A HTML'),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='body_b',
            field=models.TextField(blank=True, default='', help_text='HTML in the bottom portion of the page.  Not HTML validated, Do not edit here, be careful.', verbose_name='Body B HTML'),
        ),
    ]
