# Generated by Django 3.2.12 on 2022-05-06 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20220428_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpc_taxonomyterm',
            name='weight',
            field=models.IntegerField(default=99, max_length=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='dpc_academicpage',
            name='parent_code',
            field=models.ForeignKey(blank=True, default='', help_text='This will unite this program with another program in a relationship such as Major/Concentration.', limit_choices_to=models.Q(('program_type_id', 'PT_DEGR')), null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.dpc_academicpage', to_field='unique_program_code', verbose_name='Parent Code'),
        ),
    ]
