# Generated by Django 3.2.12 on 2022-05-06 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20220506_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpc_taxonomyterm',
            name='weight',
            field=models.IntegerField(default=99, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
