# Generated by Django 3.2.12 on 2022-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_dpc_taxonomyterm_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpc_academicpage',
            name='slug',
            field=models.SlugField(default='', max_length=80),
        ),
    ]
